export interface SeniorProgram {
    _id: string,
    seniorProgramId: string,
    managementId: string,
    trainingCenterName: string,
    centerShorBizName: string,
    trainingCenterBusinessId:string, 
    contactPerson: string,
    contactPhoneNumber: string,
    websiteUrl: string,
    videoUrl: string,
    latitude: string,
    longitute: string,
    addressLine1: string,
    addressLine2: string,
    cityName: string,
    state: string,
    zipcode: string,
    countryName: string,
    managementName: string,
    approvedBy: string,
    approvedDate: string,
    approvedStatus: string
}